
server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  server:
    eureka.server.enable-self-preservation: false
  instance:
    hostname: ${EUREKA_HOST_NAME:localhost}
  client:
    registerWithEureka: ${BOOL_REGISTER:false}
    fetchRegistry: ${BOOL_FETCH:false}
    serviceUrl:
      defaultZone: ${EUREKA_URL_LIST:http://localhost:8761/eureka/}

